CREATE TABLE IF NOT EXISTS `games` (
  `id` BIGINT(11)   UNSIGNED    NOT NULL AUTO_INCREMENT,
  `created_on`      DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_modified`   DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
